# Generated by Django 2.2 on 2019-05-05 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20190505_1330'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogpost',
            options={'ordering': ['-publish_date', 'timestamp', 'update']},
        ),
    ]
