# Generated by Django 2.2 on 2019-05-05 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20190505_1338'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogpost',
            options={'ordering': ['-publish_date', '-update', '-timestamp']},
        ),
    ]
